language: php

php:
  - 7.2
  - 7.3
  - 7.4

sudo: false

env:
  matrix:
    - DB=sqlite db_dsn='sqlite:///:memory:'
  global:
    - DEFAULT=1

matrix:
  fast_finish: true

  include:
    - php: 7.2
      env: PHPCS=1 DEFAULT=0

    - php: 7.2
      env: COVERALLS=1 DEFAULT=0

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - sh -c "if [ '$PHPCS' = '1' ]; then composer require --dev cakephp/cakephp-codesniffer; fi"
#  - sh -c "if [ '$COVERALLS' = '1' ]; then mkdir -p build/logs; fi"
  - command -v phpenv > /dev/null && phpenv rehash || true

script:
#  - sh -c "if [ '$COVERALLS' = '1' ]; then vendor/bin/phpunit --stderr --coverage-clover build/logs/clover.xml; fi"
#  - sh -c "if [ '$COVERALLS' = '1' ]; then ls -la build/logs; fi"
#  - sh -c "if [ '$COVERALLS' = '1' ]; then vendor/bin/coveralls -v; fi"
  - sh -c "if [ '$DEFAULT' = '1' ]; then vendor/bin/phpunit --stderr; fi"
  - sh -c "if [ '$PHPCS' = '1' ]; then vendor/bin/phpcs -n -p --extensions=php --standard=vendor/cakephp/cakephp-codesniffer/CakePHP --ignore=vendor --ignore=docs --ignore=tests/bootstrap.php . ; fi"

notifications:
  email: false
