language: php

php:
  - 7.2
  - 7.3
  - 7.4

sudo: false

env:
  matrix:
    - DB=sqlite db_dsn='sqlite:///:memory:'
  global:
    - DEFAULT=1

matrix:
  fast_finish: true

  include:
    - php: 7.2
      env: PHPCS=1 DEFAULT=0

    - php: 7.2
      env: COVERAGE=1 DEFAULT=0

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - if [[ PHPCS == 1 ]]; then composer require --dev cakephp/cakephp-codesniffer ; fi
  - command -v phpenv > /dev/null && phpenv rehash || true

script:
  - if [[ COVERAGE == 1 ]]; then vendor/bin/phpunit --coverage-clover=clover.xml || true ; fi
  - if [[ COVERAGE == 1 ]]; then wget -O codecov.sh https://codecov.io/bash ; fi
  - if [[ COVERAGE == 1 ]]; then bash codecov.sh ; fi

  - if [[ DEFAULT == 1 ]]; then vendor/bin/phpunit --stderr ; fi

  - if [[ PHPCS == 1 ]]; then vendor/bin/phpcs -n -p --extensions=php --standard=vendor/cakephp/cakephp-codesniffer/CakePHP --ignore=vendor --ignore=docs --ignore=tests/bootstrap.php . ; fi

notifications:
  email: false
